### ISSUE TITLE
Boss marker not working

### ISSUE THREAD

**Issue by loveuseless** [mpstark/SPT-DynamicMaps#12]
Firstly, awesome mod.
Secondly, i have a shit ton of mods and there can be conflicts, and i can provide any logs to help and solve that

**Comment by mpstark** [comment]
Some additional info:

- What bosses did you notice not being marked?
- On what map?
- Are you playing Fika or SIT?
- Can I have a screen grab of your current dynamic maps config in the F12 menu?

**Comment by loveuseless** [comment]
I can't see any bosses.
STP, no fika.
i didn't try streets but all others are bugged for sure.

![image](https://github.com/mpstark/SPT-DynamicMaps/assets/53101813/b6c03c79-028b-41be-8361-d46f47a2e967)
![image](https://github.com/mpstark/SPT-DynamicMaps/assets/53101813/cbcd973c-03ed-42cd-a52f-08ebe1295f43)

**Comment by loveuseless** [comment]
Ok i did a bit of testing and It works fine if i have scav markers are ON. Witch i didn't had and do not rly wanna have

![image](https://github.com/mpstark/SPT-DynamicMaps/assets/53101813/4a9ca8e1-f5de-4955-b0ea-800ab5f9d018)
![image](https://github.com/mpstark/SPT-DynamicMaps/assets/53101813/dc61ce43-b5c3-44d7-a267-d93f86e11d19)

**Comment by mpstark** [comment]
Ah, I found the issue -- I've got an optimization that turns off the other player marker module if none of the markers are enabled, but it doesn't take the boss option.

If you're not playing coop, show friendly players does not do anything, so enabling that should allow Boss Markers to work without Scav option checked. I will fix this in the next version.

**Comment by mpstark** [comment]
This should now be fixed with 0.3.1.2
